version: "3"
services:
  redis:
    container_name: redix
    image: redis
    ports:
      - "6379:6379"
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "example"
      POSTGRES_DB: "some_db"
    ports:
      - "5432:5432"
